import '../models/teacher_model.dart';

final sampleTeacher_1 = [
  TeacherModel(
    userId: 'U005',
    name: 'Nguyen Van A',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=57',
    email: 'nguyenvana@example.com',
    phoneNumber: '0901234567',
  ),
  TeacherModel(
    userId: 'U006',
    name: 'Tran Thi B',
    isAccepted: false,
    avatar: 'https://i.pravatar.cc/150?img=56',
    email: 'tranthib@example.com',
    phoneNumber: '0902345678',
  ),
  TeacherModel(
    userId: 'U007',
    name: 'Le Van C',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=55',
    email: 'levanc@example.com',
    phoneNumber: '0903456789',
  ),
  TeacherModel(
    userId: 'U008',
    name: 'Pham Thi D',
    isAccepted: false,
    avatar: 'https://i.pravatar.cc/150?img=54',
    email: 'phamthid@example.com',
    phoneNumber: '0904567890',
  ),
  TeacherModel(
    userId: 'U009',
    name: 'Hoang Van E',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=53',
    email: 'hoangvane@example.com',
    phoneNumber: '0905678901',
  ),
  TeacherModel(
    userId: 'U010',
    name: 'Vo Thi F',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=52',
    email: 'vothif@example.com',
    phoneNumber: '0906789012',
  ),
  TeacherModel(
    userId: 'U011',
    name: 'Dang Van G',
    isAccepted: false,
    avatar: 'https://i.pravatar.cc/150?img=51',
    email: 'dangvang@example.com',
    phoneNumber: '0907890123',
  ),
];

final sampleTeacher_2 = [
  TeacherModel(
    userId: 'U012',
    name: 'Nguyen Van L',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=58',
    email: 'nguyenvanl@example.com',
    phoneNumber: '0908901234',
  ),
  TeacherModel(
    userId: 'U013',
    name: 'Tran Thi M',
    isAccepted: false,
    avatar: 'https://i.pravatar.cc/150?img=59',
    email: 'tranthim@example.com',
    phoneNumber: '0909012345',
  ),
  TeacherModel(
    userId: 'U014',
    name: 'Le Van N',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=60',
    email: 'levann@example.com',
    phoneNumber: '0909123456',
  ),
  TeacherModel(
    userId: 'U015',
    name: 'Pham Thi P',
    isAccepted: false,
    avatar: 'https://i.pravatar.cc/150?img=61',
    email: 'phamthip@example.com',
    phoneNumber: '0909234567',
  ),
];

final sampleTeacher_3 = [
  TeacherModel(
    userId: 'U016',
    name: 'Nguyen Van L',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=62',
    email: 'nguyenvanl2@example.com',
    phoneNumber: '0909345678',
  ),
  TeacherModel(
    userId: 'U017',
    name: 'Tran Thi M',
    isAccepted: false,
    avatar: 'https://i.pravatar.cc/150?img=63',
    email: 'tranthim2@example.com',
    phoneNumber: '0909456789',
  ),
  TeacherModel(
    userId: 'U018',
    name: 'Le Van N',
    isAccepted: true,
    avatar: 'https://i.pravatar.cc/150?img=64',
    email: 'levann2@example.com',
    phoneNumber: '0909567890',
  ),
  TeacherModel(
    userId: 'U019',
    name: 'Pham Thi P',
    isAccepted: false,
    avatar: 'https://i.pravatar.cc/150?img=65',
    email: 'phamthip2@example.com',
    phoneNumber: '0909678901',
  ),
];
