import '../models/comment_model.dart';
import '../models/post_model.dart';

List<PostModel> samplePosts = [
  PostModel(
    id: '1',
    creatorName: 'John Doe',
    creatorAvatar: 'https://i.pravatar.cc/150?img=1',
    content: 'This is a beautiful day!',
    imageUrl: ['https://picsum.photos/400/300', 'https://picsum.photos/400/399', 'https://picsum.photos/400/398'],
    createdAt: DateTime.now().subtract(Duration(days: 1)),
    likes: 120,
    views: 450,
    comments: [
      CommentModel(
        id: '101',
        commenterName: 'Jane Smith',
        commentText: 'Amazing view!',
        commentedAt: DateTime.now().subtract(Duration(hours: 10)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=2',
      ),
      CommentModel(
        id: '102',
        commenterName: 'Alice Brown',
        commentText: 'Wow, where is this?',
        commentedAt: DateTime.now().subtract(Duration(hours: 8)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=3',
      ),
      CommentModel(
        id: '101',
        commenterName: 'Jane Smith',
        commentText: 'Amazing view!',
        commentedAt: DateTime.now().subtract(Duration(hours: 10)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=4',
      ),
      CommentModel(
        id: '102',
        commenterName: 'Alice Brown',
        commentText: 'Wow, where is this?',
        commentedAt: DateTime.now().subtract(Duration(hours: 8)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=5',
      ),
      CommentModel(
        id: '101',
        commenterName: 'Jane Smith',
        commentText: 'Amazing view!',
        commentedAt: DateTime.now().subtract(Duration(hours: 10)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=6',
      ),
      CommentModel(
        id: '102',
        commenterName: 'Alice Brown',
        commentText: 'Wow, where is this?',
        commentedAt: DateTime.now().subtract(Duration(hours: 8)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=7',
      ),
      CommentModel(
        id: '101',
        commenterName: 'Jane Smith',
        commentText: 'Amazing view!',
        commentedAt: DateTime.now().subtract(Duration(hours: 10)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=8',
      ),
      CommentModel(
        id: '102',
        commenterName: 'Alice Brown',
        commentText: 'Wow, where is this?',
        commentedAt: DateTime.now().subtract(Duration(hours: 8)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=9',
      ),
    ],
  ),
  PostModel(
    id: '2',
    creatorName: 'Emily Clark',
    creatorAvatar: 'https://i.pravatar.cc/150?img=2',
    content: 'Nature is so refreshing 🌿',
    imageUrl: ['https://picsum.photos/400/301'],
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    likes: 200,
    views: 600,
    comments: [
      CommentModel(
        id: '201',
        commenterName: 'Michael Scott',
        commentText: 'Couldn’t agree more!',
        commentedAt: DateTime.now().subtract(Duration(hours: 15)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=4',
      ),
    ],
  ),
  PostModel(
    id: '3',
    creatorName: 'Chris Evans',
    creatorAvatar: 'https://i.pravatar.cc/150?img=3',
    content: 'Throwback to my favorite trip 🏖️',
    createdAt: DateTime.now().subtract(Duration(days: 5)),
    likes: 350,
    views: 900,
    comments: [],
  ),
  PostModel(
    id: '4',
    creatorName: 'Sophia Martinez',
    creatorAvatar: 'https://i.pravatar.cc/150?img=4',
    content: 'A cup of coffee and a good book ☕📖',
    imageUrl: ['https://picsum.photos/400/303'],
    createdAt: DateTime.now().subtract(Duration(days: 3)),
    likes: 180,
    views: 500,
    comments: [
      CommentModel(
        id: '301',
        commenterName: 'Ethan Moore',
        commentText: 'Perfect combo!',
        commentedAt: DateTime.now().subtract(Duration(hours: 20)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=5',
      ),
    ],
  ),
  PostModel(
    id: '5',
    creatorName: 'Liam Johnson',
    creatorAvatar: 'https://i.pravatar.cc/150?img=5',
    content: 'Sunset vibes 🌅',
    imageUrl: ['https://picsum.photos/400/304'],
    createdAt: DateTime.now().subtract(Duration(days: 4)),
    likes: 300,
    views: 800,
    comments: [
      CommentModel(
        id: '401',
        commenterName: 'Olivia Taylor',
        commentText: 'Stunning colors!',
        commentedAt: DateTime.now().subtract(Duration(hours: 5)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=6',
      ),
    ],
  ),
  PostModel(
    id: '6',
    creatorName: 'Isabella Lee',
    creatorAvatar: 'https://i.pravatar.cc/150?img=6',
    content: 'Exploring the city streets 🏙️',
    createdAt: DateTime.now().subtract(Duration(days: 6)),
    likes: 250,
    views: 700,
    comments: [],
  ),
  PostModel(
    id: '7',
    creatorName: 'James Brown',
    creatorAvatar: 'https://i.pravatar.cc/150?img=7',
    content: 'Workout session completed 💪',
    imageUrl: ['https://picsum.photos/400/306'],
    createdAt: DateTime.now().subtract(Duration(days: 1)),
    likes: 150,
    views: 400,
    comments: [
      CommentModel(
        id: '501',
        commenterName: 'Mia Davis',
        commentText: 'Great job!',
        commentedAt: DateTime.now().subtract(Duration(hours: 7)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=7',
      ),
    ],
  ),
  PostModel(
    id: '8',
    creatorName: 'Charlotte Garcia',
    creatorAvatar: 'https://i.pravatar.cc/150?img=8',
    content: 'Cooking up something delicious 🍳',
    imageUrl: ['https://picsum.photos/400/307'],
    createdAt: DateTime.now().subtract(Duration(days: 7)),
    likes: 400,
    views: 1000,
    comments: [
      CommentModel(
        id: '601',
        commenterName: 'Henry Wilson',
        commentText: 'Yummy! What’s the recipe?',
        commentedAt: DateTime.now().subtract(Duration(hours: 12)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=8',
      ),
    ],
  ),
  PostModel(
    id: '9',
    creatorName: 'Ella Adams',
    creatorAvatar: 'https://i.pravatar.cc/150?img=9',
    content: 'Road trip memories 🚗',
    imageUrl:[ 'https://picsum.photos/400/308'],
    createdAt: DateTime.now().subtract(Duration(days: 8)),
    likes: 500,
    views: 1200,
    comments: [
      CommentModel(
        id: '701',
        commenterName: 'Lucas Harris',
        commentText: 'So much fun!',
        commentedAt: DateTime.now().subtract(Duration(hours: 14)),
        commenterAvatar: 'https://i.pravatar.cc/150?img=9',
      ),
    ],
  ),
  PostModel(
    id: '10',
    creatorName: 'Olivia Miller',
    creatorAvatar: 'https://i.pravatar.cc/150?img=10',
    content: 'Peaceful moments by the lake 🌊',
    createdAt: DateTime.now().subtract(Duration(days: 9)),
    likes: 420,
    views: 950,
    comments: [],
  ),
];
